%=========================================================================%
% Figure displaying individual time-series of behavior and model fits
% from Correa CMC, et al. (2018) J.Neuro (https://doi.org/10.1523/JNEUROSCI.0457-18.2018)
% Needs Matlab R2014b or more recent, and matlab's Statistics and Machine Learning toolbox
% Author: Mael Lebreton
% email: mael.lebreton@unige.ch
%=========================================================================%

clc
clear
close all

% load data and estimated model paramaters
load('PARAMS')
load('SUB_DATA')

% specs
subjects    = 1:32;
nsub        = numel(subjects);
nmodel      = 18;
KK = [1 0 1 0 0 0;...
    1 0 1 0 0 0;...
    1 0 1 1 0 0;...
    1 0 1 0 1 0;...
    1 0 1 0 1 0;...
    1 0 1 1 1 0;...
    1 0 1 0 1 1;...
    1 0 1 0 1 1;...
    1 0 1 1 1 1;...
    1 1 1 0 0 0;...
    1 1 1 0 0 0;...
    1 1 1 1 0 0;...
    1 1 1 0 1 0;...
    1 1 1 0 1 0;...
    1 1 1 1 1 0;...
    1 1 1 0 1 1;...
    1 1 1 0 1 1;...
    1 1 1 1 1 1];

% pre-Allocate
meanLL   = NaN(nsub,1);
PSwBehav = NaN(nsub,4);
PSwModel = NaN(nsub,4);
mP       = zeros(nsub,6);

% subject loop
for ksub=1:32
    
    data = SubData(nsub).data;
    
    con  = data(:,4);                         % reward visibility (1=unconscious, 0=conscious)
    cor  = data(:,3)==3;                      % 3: block ID (1=right response rewards most, 3=left response rewards most)
    cho  = data(:,6);                         % response (1= left, 2 = right)
    out  =(data(:,5)-0.5)*-2;                 % reward (-1=punishment, 1=reward)
    
    mP(ksub,:) = parameters(ksub,:,nmodel).*KK(nmodel,:);
    
    [~,pc,~,c] = compute_model_output(mP(ksub,:),con,cho,out,nmodel);
    LL = c.*pc + (1-c).*(1-pc);
    meanLL(ksub) = nanmean(LL);
    
    % Get summary stats on switches
    pSw = 1-(c(2:end) == c(1:end-1));
    PSwBehav(ksub,:) = [
        mean(pSw(con(1:end-1)==1 & out(1:end-1)==1)),...
        mean(pSw(con(1:end-1)==1 & out(1:end-1)==-1)),...
        mean(pSw(con(1:end-1)==0 & out(1:end-1)==1)),...
        mean(pSw(con(1:end-1)==0 & out(1:end-1)==-1))];
    
    pSwm = 1-((cho(1:end-1)==1).*pc(2:end) + (cho(1:end-1)==2).*(1-pc(2:end)));
    PSwModel(ksub,:) = [
        nanmean(pSwm(con(1:end-1)==1 & out(1:end-1)==1)),...
        nanmean(pSwm(con(1:end-1)==1 & out(1:end-1)==-1)),...
        nanmean(pSwm(con(1:end-1)==0 & out(1:end-1)==1)),...
        nanmean(pSwm(con(1:end-1)==0 & out(1:end-1)==-1))];
    
    % Get Time-series
    chg_block = [0;cor(2:end)~=cor(1:end-1)];
    tb = find(chg_block==1);
    tblock = [1;tb;size(cor,1)];
    
    cor = cor*.4 +.3;
    
    pc_b    =[];
    c_b     = [];
    cor_b   = [];
        
    kk = 0;
    for kblock = 1 : sum(chg_block)
        block_size  = tblock(kblock+1)-tblock(kblock);
        stepsize    = 12;
        n_bin       = floor(block_size./stepsize);
        
        for k_bin = 1:n_bin
            kk=kk+1;
            k_in        = tblock(kblock) + (k_bin-1)*stepsize;
            k_out       = tblock(kblock) + k_bin*stepsize -1;

            pc_b(kk)    = nanmean(pc(k_in:k_out));
            c_b(kk)     = nanmean(c(k_in:k_out));
            cor_b(kk)   = nanmean(cor(k_in:k_out));
        end
    end
    
    figure('Units', 'pixels', ...
        'Position', [700 200 400 400]);
    set(gcf,'Color',[1,1,1])
    
    % Subplot 1
    %==========
    hold on
    
    C1          = cor_b;
    C1(C1<.5)   = NaN;
    C2          = cor_b;
    C2(C2>.5)   = NaN;
    
    
    hPC     = plot(pc_b);
    hC1     = plot(C1);
    hC2     = plot(C2);
    hC      = plot(c_b); % popuylation statistics (mean and sem accross subjects
    
    set(hC                              , ...
        'LineStyle'       , ':'         , ...
        'LineWidth'       , .5          , ...
        'Color'           , .5*[1,1,1]  , ...
        'Marker'          , 'o'         , ...
        'MarkerSize'      , 4           , ...
        'MarkerEdgeColor' , .5*[1,1,1]  , ...
        'MarkerFaceColor' , .8*[1,1,1]     );
    
    set(hPC                             , ...
        'LineStyle'       , '-'         , ...
        'LineWidth'       , 2           , ...
        'Color'           , [0 .4 0]   , ...
        'Marker'          , 'none'         );
    
    set(hC1                           , ...
        'LineStyle'       , '-'       , ...
        'Marker'          , 'none'    , ...
        'LineWidth'       , 6         , ...
        'Color'           , [1,.6,.4]     );
    
    set(hC2                           , ...
        'LineStyle'       , '-'       , ...
        'Marker'          , 'none'    , ...
        'LineWidth'       , 6         , ...
        'Color'           , [.4,.6,1]     );
    
    hXLabel = xlabel ('Blocks of 12 trials');
    hYLabel = ylabel('choose left (behavior vs model)');
    
    set(gca, ...
        'PlotBoxAspectRatio', [1,1,1], ...
        'Box'         , 'off'     , ...
        'TickDir'     , 'out'     , ...
        'TickLength'  , [.02 .02] , ...
        'YMinorTick'  , 'on'      , ...
        'XMinorTick'  , 'on'      , ...
        'XColor'      , [.0 .0 .0], ...
        'XLim'        , [1 100]   , ...
        'YColor'      , [.0 .0 .0], ...
        'LineWidth'   , .5        , ...
        'FontName'   , 'Arial' );
    
    set([hXLabel, hYLabel] , ...
        'FontName'   , 'Arial'      , ...
        'FontSize'   , 10          );

end

