%=========================================================================%
% Figure/analyses of Bayesian Model Comparison
% from Correa CMC, et al. (2018) J.Neuro (https://doi.org/10.1523/JNEUROSCI.0457-18.2018)
% Needs Matlab R2014b or more recent, and matlab's Statistics and Machine Learning toolbox
% Author: Mael Lebreton
% email: mael.lebreton@unige.ch
%=========================================================================%
clc
clear
close all

% load data, BMC outputs and estimated model parameters
load('BMC')
load('PARAMS')
rng('shuffle')

% specs
subjects    = 1:32;
nmodel      = 18;
nsub        = numel(subjects);

% Figure: Baysian model comparison
%==============================
h1 = figure('Units', 'pixels', ...
    'Position', [200 50 600 300]);

set(gcf,'Color',[1,1,1])
%% subplot 1
subplot(1,2,1)
hold on
hData = bar(100*outBMC.ep);
set(hData,...
    'FaceColor',[1,1,1],...
    'EdgeColor',[0,0,0])

hFreq = plot(100*outBMC.Ef,'o');
set(hFreq,...
    'MarkerFaceColor',.8*[1,1,1],...
    'MarkerEdgeColor',[0,0,0])
hYLabel = ylabel('%');
hXLabel = xlabel('Model #');
hLegend = legend({'Exceedence probability','Expected frequency'});

set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'YMinorTick'  , 'on'      , ...
    'XColor'      , [.0 .0 .0], ...
    'YLim'        ,[0 100]      ,...
    'XLim'        ,[0 19]     ,...
    'XTick'       ,1:18         ,...
    'YColor'      , [.0 .0 .0], ...
    'LineWidth'   , .5        , ...
    'FontName'   , 'Arial' );

set([hXLabel,hYLabel,hLegend], ...
    'FontName'   , 'Arial'      , ...
    'FontSize'   , 10          );

set(hLegend,'Location','NorthWest')


%% subplot 2
% If you look into Wagenmakers (2007) you will see that he defines it differently.
% The BIC approximation to the Bayes Factor he advocates for BF_01 is given by exp( (BIC_1 - BIC_0)/2 ) (see page 796).
% Reference: Wagenmakers, E.-J. (2007). A practical solution to the pervasive problems of p values. Psychonomic Bulletin & Review, 14(5), 779?804. doi:10.3758/BF03194105

subplot(1,2,2)
hold on
BF = bic - (repmat(bic(:,18),1,18));
mtp = mean(BF);
stp = std(BF)./sqrt(32);

hYLabel = ylabel('\delta BIC (BIC(18)-BIC(#))');
hXLabel = xlabel('Model #');

hData = bar(mtp);
set(hData,...
    'FaceColor','none',...
    'EdgeColor',[0,0,0])

errorbar(mtp,stp,'k',...
    'LineStyle','none')

set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'YMinorTick'  , 'on'      , ...
    'XColor'      , [.0 .0 .0], ...
    'XLim'        ,[0 19]     ,...
    'XTick'       ,1:18         ,...
    'YColor'      , [.0 .0 .0], ...
    'LineWidth'   , .5        , ...
    'FontName'   , 'Arial' );

set([hXLabel,hYLabel], ...
    'FontName'   , 'Arial'      , ...
    'FontSize'   , 10          );
