%=========================================================================%
% Figure displaying the vbehavioral switches after each type of feedback
% (pos/neg and masked/unmasked)
% from Correa CMC, et al. (2018) J.Neuro (https://doi.org/10.1523/JNEUROSCI.0457-18.2018)
% Needs Matlab R2014b or more recent, and matlab's Statistics and Machine Learning toolbox
% Author: Mael Lebreton
% email: mael.lebreton@unige.ch
%=========================================================================%
clc
clear
close all

% load data
load('SUB_DATA')

% specs
subjects    = 1:32;

% pre-allocate
PSwBehav = NaN(numel(subjects),4);

% subject loop
for nsub=subjects

    data    = SubData(nsub).data;
    tr      = data(:,6) ~=0;
    con     = data(tr,4);                         % reward visibility (1=unconscious, 0=conscious)
    cor     = data(tr,3)==3;                      % 3: block ID (1=right response rewards most, 3=left response rewards most)
    cho     = data(tr,6);                         % response (1= left, 2 = right)
    out     =(data(tr,5)-0.5)*-2;                 % reward (-1=punishment, 1=reward)
    
    % Get summary stats on switches
    pSw = 1-(cho(2:end) == cho(1:end-1));
    PSwBehav(nsub,:) = [
        mean(pSw(con(1:end-1)==1 & out(1:end-1)==1)),...
        mean(pSw(con(1:end-1)==1 & out(1:end-1)==-1)),...
        mean(pSw(con(1:end-1)==0 & out(1:end-1)==1)),...
        mean(pSw(con(1:end-1)==0 & out(1:end-1)==-1))];
end

% STATS
XX = [PSwBehav(:,2)-PSwBehav(:,1),PSwBehav(:,4)-PSwBehav(:,3)];

% PLOTS
colrand_sub = 0.8 + rand(nsub,3)./5;
MS = 5;

h1 = figure;

set(gcf,'Color',[1,1,1])
hold on
X       = 1:4;
Xall    = 100*PSwBehav(:,:);

for k_sub = subjects
       
   plot((1:2)+ .3*(rand(1,2)-.5), Xall(k_sub,1:2),'-o',...
       'MarkerSize',MS,...
       'Color',.65*colrand_sub(k_sub,:),...
       'MarkerFaceColor',.8*colrand_sub(k_sub,:),...
       'MarkerEdgeColor',.5*colrand_sub(k_sub,:))  
          
   plot((3:4)+ .3*(rand(1,2)-.5), Xall(k_sub,3:4),'-o',...
       'MarkerSize',MS,...
       'Color',.65*colrand_sub(k_sub,:),...
       'MarkerFaceColor',.8*colrand_sub(k_sub,:),...
       'MarkerEdgeColor',.5*colrand_sub(k_sub,:)) 
end

hXall = errorbar(X(1:2)+.05,mean(Xall(:,1:2)),std(Xall(:,1:2))./sqrt(32));
set(hXall                             , ...
    'LineStyle'       , '-'         , ...
    'LineWidth'       , 1.5          , ...
    'Color'           , 0*[1,1,1]  , ...
    'Marker'          , 'd'         , ...
    'MarkerSize'      , 6           , ...
    'MarkerEdgeColor' , 0*[1,1,1]   , ...
    'MarkerFaceColor' , 0*[1,1,1]     );
hXall = errorbar(X(3:4)+.05,mean(Xall(:,3:4)),std(Xall(:,3:4))./sqrt(32));

set(hXall                             , ...
    'LineStyle'       , '-'         , ...
    'LineWidth'       , 1.5          , ...
    'Color'           , 0*[1,1,1]  , ...
    'Marker'          , 'd'         , ...
    'MarkerSize'      , 6           , ...
    'MarkerEdgeColor' , 0*[1,1,1]   , ...
    'MarkerFaceColor' , 0*[1,1,1]     );


XL = {'M+','M-','UM+','UM-'};

set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'YMinorTick'  , 'on'      , ...
    'XColor'      , [.0 .0 .0], ...
    'YLim'        ,[0 100]      ,...
    'XLim'        ,[0.5 4.5]      ,...
    'XTick'       ,1:4      ,...
    'XTickLabel'  ,XL         ,...
    'YColor'      , [.0 .0 .0], ...
    'LineWidth'   , .5        , ...
    'FontName'   , 'Arial' );

hYLabel = ylabel('(%) Switches');
hXLabel = xlabel('Prev. Trial');

set([hYLabel,hYLabel], ...
    'FontName'   , 'Arial'      , ...
    'FontSize'   , 10          );

legend('all subjects')


% toPPT(h1,'format','vec');